import json

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import RedirectResponse
from google_auth_oauthlib.flow import Flow

from app.config import settings


router = APIRouter(
    prefix="/auth",
    tags=["Authentication"]
)

TOKEN_FILE = "token.json"

# In-memory store for PKCE code verifiers, keyed by OAuth state.
# Fine for single-user localhost hackathon MVP.
_oauth_states: dict[str, str] = {}


def create_google_flow():
    """Create Google OAuth Flow object."""
    flow = Flow.from_client_config(
        {
            "web": {
                "client_id": settings.GOOGLE_CLIENT_ID,
                "client_secret": settings.GOOGLE_CLIENT_SECRET,
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
                "redirect_uris": [settings.GOOGLE_REDIRECT_URI]
            }
        },
        scopes=settings.GMAIL_SCOPES,
    )
    flow.redirect_uri = settings.GOOGLE_REDIRECT_URI
    return flow


@router.get("/login")
async def login():
    """Generate Google OAuth authorization URL and persist the PKCE code_verifier."""
    flow = create_google_flow()

    authorization_url, state = flow.authorization_url(
        access_type="offline",
        include_granted_scopes="true",
        prompt="consent"
    )

    # Store the code_verifier generated by authorization_url()
    # so we can reattach it during the callback.
    _oauth_states[state] = flow.code_verifier

    return {
        "authorization_url": authorization_url,
        "state": state
    }


@router.get("/callback")
async def callback(request: Request):
    """Handle Google OAuth callback — restore PKCE verifier and exchange code for tokens."""
    code = request.query_params.get("code")
    state = request.query_params.get("state")

    if not code:
        raise HTTPException(status_code=400, detail="Authorization code not found")

    if not state or state not in _oauth_states:
        raise HTTPException(status_code=400, detail="Invalid or expired OAuth state")

    # Retrieve the code_verifier that was generated during /login
    code_verifier = _oauth_states.pop(state)  # pop = use once then discard

    try:
        flow = create_google_flow()

        # Reattach the PKCE code_verifier before exchanging the code
        flow.code_verifier = code_verifier

        # Exchange authorization code for access token
        flow.fetch_token(code=code)

        credentials = flow.credentials

        token_data = {
            "token": credentials.token,
            "refresh_token": credentials.refresh_token,
            "token_uri": credentials.token_uri,
            "client_id": credentials.client_id,
            "client_secret": credentials.client_secret,
            "scopes": list(credentials.scopes) if credentials.scopes else []
        }

        # Save credentials locally (Hackathon MVP)
        with open(TOKEN_FILE, "w") as token:
            json.dump(token_data, token)

        # Redirect to React dashboard
        return RedirectResponse(url=f"{settings.FRONTEND_URL}/dashboard")

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Authentication failed: {str(e)}")
